language: php
php:
    - 5.5
    - 5.6
    - 7

matrix:
    allow_failures:
        - php: 7

before_script:
    - composer install --dev --prefer-source

script: vendor/bin/phpunit --colors --coverage-text
