language: php

php:
    - 5.6
    - 7
    - hhvm
    - nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    allow_failures:
        - php: 7
        - php: hhvm
        - php: nightly

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --colors --coverage-text
